### ISSUE TITLE
Recent updates broke creating new PM topics between normal users

### ISSUE THREAD

**Issue by geckolinux** [pfaffman/discourse-allow-pm-to-staff#1]
Hi there, it looks like the recent updates have broken sending PMs between normal users. Specifically, normal users can respond to already existing PM topics but not create new PM topics. This is the error:

![Screenshot from 2023-03-28 19-35-07](https://user-images.githubusercontent.com/2692138/228396889-18701622-b8d2-490b-b3f1-bfdaa1eced69.png)

I didn't really understand the function of the `allow_pm_allowed_pm_groups` setting, but I tried setting it to `staff,trust_level_0,trust_level_1,trust_level_2` but the problem persisted. I disabled the plugin and PMs are now working normally again.

**Comment by pfaffman** [comment]
Hey @geckolinux. 

Sorry I didn't notice or fully appreciate this sooner.

I am pretty sure that I fixed this, which got broken, I think, when they changed to the `allowed_pm_pm_groups` setting.

There is now https://meta.discourse.org/t/allow-pm-to-staff/260946

It sounds like there is still an issue accessing user profiles with the plugin enabled. I'm confused how that could be, but that does't mean that it's not true.

if you have a budget to throw at these problems when they occur, it would likely get me to pay closer attention. I've got one client who paid to develop the plugin and, for reasons unclear, he hasn't noticed that it's broken yet.

**Comment by geckolinux** [comment]
Hi @pfaffman , thanks for the reply.

> I am pretty sure that I fixed this, which got broken, I think, when they changed to the `allowed_pm_pm_groups` setting.

Right, this bug report about not being able to send PMs between normal users is fixed with the current state of the plugin.

The issue with not being able to see user profiles with the plugin enabled would be a separate bug report, which I can open if you like.

**Comment by pfaffman** [comment]
Have you seen the error of not being able to see uesr profiles? I can't replicate it.

**Comment by geckolinux** [comment]
> Have you seen the error of not being able to see uesr profiles? I can't replicate it.

Yes, I'm the original reporter. Did you test in a private browsing session as an anonymous user?

**Comment by pfaffman** [comment]
Thanks. Try it now.

**Comment by geckolinux** [comment]
That fixed it! Thanks very much.
